version: '3.8'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: on-failure
  nacos:
    #http://localhost:8848/nacos nacos:nacos
    container_name: nacos
    hostname: nacos
    image: nacos/nacos-server:${NACOS_VERSION}
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./conf/nacos:/home/nacos/conf
      - ./data/nacos:/home/nacos/data
      - ./logs/nacos:/home/nacos/logs
    command: tail -f /dev/null
  loki:
    #http://localhost:3100/metrics
    image: grafana/loki:${LOKI_VERSION}
    ports:
      - 3100:3100
    volumes:
      - ./conf/loki/local-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/tmp/loki
    #command: -config.file=/etc/loki/local-config.yaml
